// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace SimpleComputerShopAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20210306062109_AddCostToLaptopBrand")]
    partial class AddCostToLaptopBrand
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Entities.Models.ConfigurationCost", b =>
                {
                    b.Property<int>("ConfigurationCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ConfigurationCostId")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ConfigurationItemId")
                        .HasColumnType("integer");

                    b.Property<long>("Cost")
                        .HasColumnType("bigint");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConfigurationCostId");

                    b.HasIndex("ConfigurationItemId", "Option")
                        .IsUnique();

                    b.ToTable("ConfigurationCosts");

                    b.HasData(
                        new
                        {
                            ConfigurationCostId = 1,
                            ConfigurationItemId = 1,
                            Cost = 4567L,
                            Option = "8 GB"
                        },
                        new
                        {
                            ConfigurationCostId = 2,
                            ConfigurationItemId = 1,
                            Cost = 8788L,
                            Option = "16 GB"
                        },
                        new
                        {
                            ConfigurationCostId = 3,
                            ConfigurationItemId = 2,
                            Cost = 12334L,
                            Option = "500 GB"
                        },
                        new
                        {
                            ConfigurationCostId = 4,
                            ConfigurationItemId = 2,
                            Cost = 20000L,
                            Option = "1 TB"
                        },
                        new
                        {
                            ConfigurationCostId = 5,
                            ConfigurationItemId = 3,
                            Cost = 5076L,
                            Option = "Red"
                        },
                        new
                        {
                            ConfigurationCostId = 6,
                            ConfigurationItemId = 3,
                            Cost = 3456L,
                            Option = "Blue"
                        });
                });

            modelBuilder.Entity("Entities.Models.LaptopBrand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BrandId")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Cost")
                        .HasColumnType("bigint");

                    b.HasKey("BrandId");

                    b.HasIndex("BrandName")
                        .IsUnique();

                    b.ToTable("LaptopBrands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Dell",
                            Cost = 34987L
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Toshiba",
                            Cost = 34567L
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "HP",
                            Cost = 45676L
                        });
                });

            modelBuilder.Entity("Entities.Models.LaptopConfigurationItem", b =>
                {
                    b.Property<int>("ConfigurationItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ConfigurationItemId")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConfigurationItemId");

                    b.HasIndex("ItemName")
                        .IsUnique();

                    b.ToTable("LaptopConfigurationItems");

                    b.HasData(
                        new
                        {
                            ConfigurationItemId = 1,
                            ItemName = "Ram"
                        },
                        new
                        {
                            ConfigurationItemId = 2,
                            ItemName = "HDD"
                        },
                        new
                        {
                            ConfigurationItemId = 3,
                            ItemName = "Colour"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
